language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: script
  script: mvn deploy -s settings.xml -DBintrayKey=$BintrayKey -B
  on:
    branch: master
    tags: true